{% set version = '1.7-0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-plm
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/plm_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/plm/plm_{{ version }}.tar.gz
  sha256: 43512caba0cbbfe7ee2c92e6e34cea5e087e5cbfa5868089a81c01d2517fcbe4

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-formula >=0.2_0
    - r-mass
    - r-bdsmatrix
    - r-lattice
    - r-lmtest
    - r-maxlik
    - r-nlme
    - r-sandwich
    - r-zoo
  run:
    - r-base
    - r-formula >=0.2_0
    - r-mass
    - r-bdsmatrix
    - r-lattice
    - r-lmtest
    - r-maxlik
    - r-nlme
    - r-sandwich
    - r-zoo

test:
  commands:
    - $R -e "library('plm')"           # [not win]
    - "\"%R%\" -e \"library('plm')\""  # [win]

about:
  home: https://cran.r-project.org/package=plm, https://r-forge.r-project.org/projects/plm/
  license: GPL (>= 2)
  summary: A set of estimators and tests for panel data econometrics.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: plm
# Version: 1.7-0
# Date: 2019-01-03
# Title: Linear Models for Panel Data
# Authors@R: c(person(given = "Yves",      family = "Croissant",    role = c("aut", "cre"), email = "yves.croissant@univ-reunion.fr"), person(given = "Giovanni",  family = "Millo",        role = "aut", email = "Giovanni.Millo@Generali.com"), person(given = "Kevin",     family = "Tappe",        role = "aut", email = "kevin.tappe@bwi.uni-stuttgart.de"), person(given = "Ott",       family = "Toomet",       role = "ctb", email = "otoomet@gmail.com"), person(given = "Christian", family = "Kleiber",      role = "ctb", email = "Christian.Kleiber@unibas.ch"),  person(given = "Achim",     family = "Zeileis",      role = "ctb", email = "Achim.Zeileis@R-project.org"), person(given = "Arne",      family = "Henningsen",   role = "ctb", email = "arne.henningsen@googlemail.com"), person(given = "Liviu",     family = "Andronic",     role = "ctb", email = "landronimirc@gmail.com"), person(given = "Nina",      family = "Schoenfelder", role = "ctb", email = "nina.schoenfelder@fernuni-hagen.de"))
# Depends: R (>= 3.1.0), Formula (>= 0.2-0), stats
# Imports: MASS, bdsmatrix, zoo, nlme, sandwich, lattice, lmtest, maxLik
# Suggests: AER, car, pcse, clusterSEs, clubSandwich, pglm, spdep, splm, statmod, Ecdat, pder, stargazer, texreg, foreign, knitr, rmarkdown, bookdown
# Description: A set of estimators and tests for panel data econometrics.
# License: GPL (>= 2)
# VignetteBuilder: knitr
# URL: https://cran.r-project.org/package=plm, https://r-forge.r-project.org/projects/plm/
# Author: Yves Croissant [aut, cre], Giovanni Millo [aut], Kevin Tappe [aut], Ott Toomet [ctb], Christian Kleiber [ctb], Achim Zeileis [ctb], Arne Henningsen [ctb], Liviu Andronic [ctb], Nina Schoenfelder [ctb]
# Maintainer: Yves Croissant <yves.croissant@univ-reunion.fr>
# Repository: CRAN
# Repository/R-Forge/Project: plm
# Repository/R-Forge/Revision: 834
# Repository/R-Forge/DateTimeStamp: 2019-01-03 15:13:35
# Date/Publication: 2019-01-04 13:50:03 UTC
# NeedsCompilation: no
# Packaged: 2019-01-03 15:32:32 UTC; rforge
